-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U
ON USER_ID = WRITER_ID
WHERE B.STATUS = "DONE"
GROUP BY USER_ID
HAVING TOTAL_SALES >=700000
ORDER BY TOTAL_SALES;