-- 코드를 입력하세요
SELECT BOOK.CATEGORY, SUM(BOOK_SALES.SALES) as TOTAL_SALES 
FROM BOOK INNER JOIN BOOK_SALES
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%' 
GROUP BY CATEGORY
ORDER BY CATEGORY;